name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Go and Buffalo
      run: |
        sudo apt-get update
        sudo apt-get install golang-go
        go get -u -v github.com/gobuffalo/buffalo/buffalo
    - name: Run Buffalo (Replace with your Buffalo commands)
      run: buffalo dev  # Replace with the actual Buffalo command you need to run
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
